# Generated by Django 5.2 on 2025-04-25 04:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_membership_field_removed_from_user_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership_status',
            name='last_membership_renewal',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
