# Generated by Django 5.2 on 2025-04-29 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_last_membership_renewal_field_added_in_membership_status_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership_status',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.member', unique=True),
        ),
    ]
