version: '3.1'

services:
  db:
    image: mysql
    container_name: user-management
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: usermanagement
      MYSQL_ROOT_PASSWORD: docker
